"""add fk indexes

Revision ID: 1214670750f2
Revises: 6a8e8a8bb708
Create Date: 2026-08-21 11:52:10.283429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1214670750f2'
down_revision: Union[str, None] = '6a8e8a8bb708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admissions_facility_id'), 'admissions', ['facility_id'], unique=False)
    op.create_index(op.f('ix_atomic_instructions_recipient_facility_id'), 'atomic_instructions', ['recipient_facility_id'], unique=False)
    op.create_index(op.f('ix_bed_status_facility_id'), 'bed_status', ['facility_id'], unique=False)
    op.create_index(op.f('ix_beds_facility_id'), 'beds', ['facility_id'], unique=False)
    op.create_index(op.f('ix_beds_ward_id'), 'beds', ['ward_id'], unique=False)
    op.create_index(op.f('ix_equipment_status_facility_id'), 'equipment_status', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facilities_country_id'), 'facilities', ['country_id'], unique=False)
    op.create_index(op.f('ix_facilities_district_id'), 'facilities', ['district_id'], unique=False)
    op.create_index(op.f('ix_facilities_state_id'), 'facilities', ['state_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_facility_id'), 'inventory_transactions', ['facility_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_product_id'), 'inventory_transactions', ['product_id'], unique=False)
    op.create_index(op.f('ix_ot_schedules_facility_id'), 'ot_schedules', ['facility_id'], unique=False)
    op.create_index(op.f('ix_ot_schedules_ward_id'), 'ot_schedules', ['ward_id'], unique=False)
    op.create_index(op.f('ix_patient_activity_facility_id'), 'patient_activity', ['facility_id'], unique=False)
    op.create_index(op.f('ix_staff_attendance_facility_id'), 'staff_attendance', ['facility_id'], unique=False)
    op.create_index(op.f('ix_user_scopes_user_id'), 'user_scopes', ['user_id'], unique=False)
    op.create_index(op.f('ix_wards_facility_id'), 'wards', ['facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wards_facility_id'), table_name='wards')
    op.drop_index(op.f('ix_user_scopes_user_id'), table_name='user_scopes')
    op.drop_index(op.f('ix_staff_attendance_facility_id'), table_name='staff_attendance')
    op.drop_index(op.f('ix_patient_activity_facility_id'), table_name='patient_activity')
    op.drop_index(op.f('ix_ot_schedules_ward_id'), table_name='ot_schedules')
    op.drop_index(op.f('ix_ot_schedules_facility_id'), table_name='ot_schedules')
    op.drop_index(op.f('ix_inventory_transactions_product_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_facility_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_facilities_state_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_country_id'), table_name='facilities')
    op.drop_index(op.f('ix_equipment_status_facility_id'), table_name='equipment_status')
    op.drop_index(op.f('ix_beds_ward_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_facility_id'), table_name='beds')
    op.drop_index(op.f('ix_bed_status_facility_id'), table_name='bed_status')
    op.drop_index(op.f('ix_atomic_instructions_recipient_facility_id'), table_name='atomic_instructions')
    op.drop_index(op.f('ix_admissions_facility_id'), table_name='admissions')
    # ### end Alembic commands ###
