"""INT-01..14: intelligence module tables

Revision ID: 8b2738bf63dd
Revises: 6a8e8a8bb708
Create Date: 2026-08-21 12:15:09.392477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2738bf63dd'
down_revision: Union[str, None] = '6a8e8a8bb708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_number')
    )
    op.create_table('federation_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('weekly_seasonal_index', sa.Float(), nullable=False),
    sa.Column('monthly_seasonal_index', sa.Float(), nullable=False),
    sa.Column('demand_trend', sa.Float(), nullable=False),
    sa.Column('consumption_per_1000_visits', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('lead_time_mean', sa.Float(), nullable=False),
    sa.Column('lead_time_variance', sa.Float(), nullable=False),
    sa.Column('forecast_mae', sa.Float(), nullable=False),
    sa.Column('forecast_bias', sa.Float(), nullable=False),
    sa.Column('stockout_frequency', sa.Float(), nullable=False),
    sa.Column('surge_multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['federation_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('federation_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('raw_records_shared', sa.Integer(), nullable=False),
    sa.Column('weekly_seasonal_index', sa.Float(), nullable=False),
    sa.Column('monthly_seasonal_index', sa.Float(), nullable=False),
    sa.Column('demand_trend', sa.Float(), nullable=False),
    sa.Column('consumption_per_1000_visits', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=False),
    sa.Column('lead_time_mean', sa.Float(), nullable=False),
    sa.Column('lead_time_variance', sa.Float(), nullable=False),
    sa.Column('forecast_mae', sa.Float(), nullable=False),
    sa.Column('forecast_bias', sa.Float(), nullable=False),
    sa.Column('stockout_frequency', sa.Float(), nullable=False),
    sa.Column('surge_multiplier', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['federation_rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('recent', sa.Float(), nullable=False),
    sa.Column('percent_change', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('forecast_demand', sa.Float(), nullable=False),
    sa.Column('projected_stock', sa.Float(), nullable=False),
    sa.Column('stockout_day', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.Enum('RECENT_AVERAGE', 'SARIMA', 'STATE_SPACE', 'DECOMPOSABLE', name='forecast_model'), nullable=False),
    sa.Column('range_low', sa.Float(), nullable=False),
    sa.Column('range_high', sa.Float(), nullable=False),
    sa.Column('range_source', sa.Enum('MODEL_NATIVE', 'RESIDUAL', name='range_source'), nullable=False),
    sa.Column('fallback_level', sa.Enum('LOCAL', 'DISTRICT', 'STATE', 'NATIONAL', 'BRICS', name='fallback_level'), nullable=False),
    sa.Column('footfall_adjustment_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.Enum('NORMAL', 'WATCH', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('days_to_stockout', sa.Integer(), nullable=True),
    sa.Column('forecast_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('candidate_model', sa.Enum('RECENT_AVERAGE', 'SARIMA', 'STATE_SPACE', 'DECOMPOSABLE', name='candidate_model'), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('cv_mase', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('point', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_points')
    op.drop_table('forecast_metrics')
    op.drop_table('alerts')
    op.drop_table('forecasts')
    op.drop_table('anomalies')
    op.drop_table('federation_profiles')
    op.drop_table('federation_metrics')
    op.drop_table('federation_rounds')
    # ### end Alembic commands ###
