"""add comm module tables (COMM-01-05)

Revision ID: c3f1a9d2b7e4
Revises: 1214670750f2
Create Date: 2026-08-21 12:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c3f1a9d2b7e4'
down_revision: Union[str, None] = '1214670750f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_key_pairs',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('comm_mailboxes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id')
    )
    op.create_table('comm_sealed_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mailbox_id', sa.UUID(), nullable=False),
    sa.Column('instruction_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('sealed_key', sa.LargeBinary(), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DELIVERED', 'READ', 'UNRECOVERABLE_KEY_LOST', name='sealed_message_status'), nullable=False),
    sa.ForeignKeyConstraint(['instruction_id'], ['atomic_instructions.id'], ),
    sa.ForeignKeyConstraint(['mailbox_id'], ['comm_mailboxes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailbox_id', 'sequence', name='uq_comm_sealed_messages_mailbox_sequence')
    )
    op.create_index(op.f('ix_comm_sealed_messages_mailbox_id'), 'comm_sealed_messages', ['mailbox_id'], unique=False)
    op.create_table('instruction_receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sealed_message_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACKNOWLEDGED', 'READ', name='receipt_status'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sealed_message_id'], ['comm_sealed_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruction_receipts_sealed_message_id'), 'instruction_receipts', ['sealed_message_id'], unique=False)
    op.create_table('comm_command_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_level', sa.Enum('DISTRICT', 'STATE', 'NATIONAL', name='comm_issuer_level'), nullable=False),
    sa.Column('from_scope_id', sa.UUID(), nullable=False),
    sa.Column('to_facility_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.Enum('COMMAND_TO', 'ADMIN_PARENT', name='graph_edge_type'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['to_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_level', 'from_scope_id', 'to_facility_id', 'edge_type', name='uq_comm_command_edges_edge')
    )
    op.create_index(op.f('ix_comm_command_edges_from_scope_id'), 'comm_command_edges', ['from_scope_id'], unique=False)
    op.create_index(op.f('ix_comm_command_edges_to_facility_id'), 'comm_command_edges', ['to_facility_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comm_command_edges_to_facility_id'), table_name='comm_command_edges')
    op.drop_index(op.f('ix_comm_command_edges_from_scope_id'), table_name='comm_command_edges')
    op.drop_table('comm_command_edges')
    op.drop_index(op.f('ix_instruction_receipts_sealed_message_id'), table_name='instruction_receipts')
    op.drop_table('instruction_receipts')
    op.drop_index(op.f('ix_comm_sealed_messages_mailbox_id'), table_name='comm_sealed_messages')
    op.drop_table('comm_sealed_messages')
    op.drop_table('comm_mailboxes')
    op.drop_table('unit_key_pairs')
    sa.Enum(name='graph_edge_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='comm_issuer_level').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='receipt_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sealed_message_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
