"""CMD-01..09: command module tables (recommendations, movements, decisions, escalations, graph results)

Revision ID: e6d59c8a1d31
Revises: 09c5a9d16153
Create Date: 2026-08-21 18:00:08.517626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6d59c8a1d31'
down_revision: Union[str, None] = '09c5a9d16153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_graph_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('required_authority', sa.String(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=True),
    sa.Column('path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope_level', sa.String(), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('problem', sa.String(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forecast_id', sa.UUID(), nullable=True),
    sa.Column('graph_result_id', sa.UUID(), nullable=True),
    sa.Column('destination_facility_id', sa.UUID(), nullable=True),
    sa.Column('required_authority', sa.String(), nullable=False),
    sa.Column('agent_explanation', sa.String(), nullable=True),
    sa.Column('origin', sa.Enum('AGENT', 'HUMAN', name='recommendation_origin'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'MODIFIED', 'REJECTED', 'ESCALATED', 'OUTDATED', 'EXECUTING', 'COMPLETED', name='recommendation_status'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('parent_recommendation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ),
    sa.ForeignKeyConstraint(['graph_result_id'], ['command_graph_results.id'], ),
    sa.ForeignKeyConstraint(['parent_recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_scope_id'), 'recommendations', ['scope_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'MODIFY', 'ESCALATE', 'SUBMIT', 'OUTDATED', name='decision_action'), nullable=False),
    sa.Column('from_status', sa.String(), nullable=False),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_recommendation_id'), 'decisions', ['recommendation_id'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('escalated_recommendation_id', sa.UUID(), nullable=True),
    sa.Column('from_authority', sa.String(), nullable=False),
    sa.Column('to_authority', sa.String(), nullable=False),
    sa.Column('unresolved_quantity', sa.Float(), nullable=False),
    sa.Column('forecast_horizon_days', sa.Integer(), nullable=False),
    sa.Column('sources_checked', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_higher_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_recommendation_id'), 'escalations', ['recommendation_id'], unique=False)
    op.create_table('recommendation_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('from_facility_id', sa.UUID(), nullable=False),
    sa.Column('to_facility_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['to_facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_movements_recommendation_id'), 'recommendation_movements', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_atomic_instructions_recommendation_id'), 'atomic_instructions', ['recommendation_id'], unique=False)
    # Not autogenerated: backend/ops/models.py deliberately omits this FK in the SQLAlchemy model
    # (backend/ops must not import backend/command — the dependency runs the other way), but the
    # database itself should still enforce real referential integrity now that the table exists.
    op.create_foreign_key(
        'fk_atomic_instructions_recommendation_id', 'atomic_instructions', 'recommendations', ['recommendation_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_atomic_instructions_recommendation_id', 'atomic_instructions', type_='foreignkey')
    op.drop_index(op.f('ix_atomic_instructions_recommendation_id'), table_name='atomic_instructions')
    op.drop_index(op.f('ix_recommendation_movements_recommendation_id'), table_name='recommendation_movements')
    op.drop_table('recommendation_movements')
    op.drop_index(op.f('ix_escalations_recommendation_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_decisions_recommendation_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_recommendations_scope_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('command_graph_results')
    # ### end Alembic commands ###
